wip

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,29 +14,25 @@ commands:
       - run:
           name: Upload Coverage Results
           command: |
+            # Download and verify the codecov binary
+            curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import # One-time step
+            curl -Os https://uploader.codecov.io/latest/linux/codecov
+            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
+            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
+            gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
+            shasum -a 256 -c codecov.SHA256SUM
+            chmod +x codecov
             # Activate our venv and generate a xml report
             . venv/bin/activate
             python -m coverage xml
-            if [ $? -eq 0 -a -f coverage.xml ]; then
-              # Download and verify the codecov binary
-              curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import # One-time step
-              curl -Os https://uploader.codecov.io/latest/linux/codecov
-              curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
-              curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
-              gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
-              shasum -a 256 -c codecov.SHA256SUM
-              chmod +x codecov
-              # Execute the binary...
-                ./codecov \
-                  -t "${CODECOV_TOKEN}" \
-                  -n "${CODECOV_PREFIX}${PYVERS}node${CIRCLE_NODE_INDEX}" \
-                  -F "${CODECOV_FLAG}" \
-                  -f ./coverage.xml \
-                  -v \
-                  -Z || echo 'Codecov upload failed'
-            else
-              echo "No coverage results found to upload."
-            fi
+            # Execute the binary...
+              ./codecov \
+                -t "${CODECOV_TOKEN}" \
+                -n "${CODECOV_PREFIX}${PYVERS}node${CIRCLE_NODE_INDEX}" \
+                -F "${CODECOV_FLAG}" \
+                -f ./coverage.xml \
+                -v \
+                -Z || echo 'Codecov upload failed'
 
   do_venv_setup:
     description: "Setup venv for testing"
